// Pre-compile JSX -> bundle.js. Zero npm install required.
// On first run, downloads @babel/standalone UMD bundle from unpkg into a local cache.
// Usage:
//   node build.js           # one-shot build (used by deploy)
//   node build.js --watch   # rebuild on every change in src/
const fs = require("fs");
const path = require("path");
const https = require("https");

const root = __dirname;
const cacheFile = path.join(root, ".babel-standalone.cjs");
const outFile = path.join(root, "bundle.js");
const srcDir = path.join(root, "src");

const order = [
  "ticker.jsx",
  "hero.jsx",
  "problem.jsx",
  "inside.jsx",
  "author.jsx",
  "proof.jsx",
  "cta.jsx",
  "faq.jsx",
  "footer.jsx",
  "app.jsx",
];

function fetchTo(url, dest, hops = 0) {
  if (hops > 5) return Promise.reject(new Error("too many redirects"));
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        res.resume();
        return resolve(fetchTo(new URL(res.headers.location, url).toString(), dest, hops + 1));
      }
      if (res.statusCode !== 200) {
        res.resume();
        return reject(new Error("HTTP " + res.statusCode + " from " + url));
      }
      const file = fs.createWriteStream(dest);
      res.pipe(file);
      file.on("finish", () => file.close(() => resolve()));
      file.on("error", reject);
    }).on("error", reject);
  });
}

async function ensureBabel() {
  if (!fs.existsSync(cacheFile)) {
    console.log("Downloading @babel/standalone (one-time, ~3 MB)...");
    await fetchTo("https://unpkg.com/@babel/standalone@7.29.0/babel.min.js", cacheFile);
    console.log("Cached at " + cacheFile);
  }
  if (typeof global.self === "undefined") global.self = global;
  return require(cacheFile);
}

function buildOnce(Babel) {
  const parts = ["/* Auto-generated by build.js. Edit src/*.jsx, then re-run `node build.js`. */"];
  for (const f of order) {
    const src = fs.readFileSync(path.join(srcDir, f), "utf8");
    const { code } = Babel.transform(src, {
      presets: [["react", { runtime: "classic" }]],
      compact: false,
    });
    parts.push("/* === src/" + f + " === */");
    parts.push(code);
  }
  fs.writeFileSync(outFile, parts.join("\n\n"));
  return fs.statSync(outFile).size;
}

(async () => {
  const watch = process.argv.includes("--watch");
  const Babel = await ensureBabel();

  const runBuild = (label) => {
    try {
      const size = buildOnce(Babel);
      console.log(label + " " + outFile + " (" + (size / 1024).toFixed(1) + " KB, " + order.length + " components)");
      return true;
    } catch (e) {
      console.error("Build error: " + e.message);
      return false;
    }
  };

  if (!watch) {
    if (!runBuild("Wrote")) process.exit(1);
    return;
  }

  runBuild("Wrote");
  console.log("Watching " + srcDir + " for changes...");

  let pending = null;
  fs.watch(srcDir, { persistent: true }, (_event, filename) => {
    if (filename && !filename.endsWith(".jsx")) return;
    clearTimeout(pending);
    pending = setTimeout(() => runBuild("Rebuilt"), 100);
  });
})().catch((e) => {
  console.error("Build failed:", e.message);
  process.exit(1);
});
