// Pre-compile JSX -> bundle.js. Zero npm install required.
// On first run, downloads @babel/standalone UMD bundle from unpkg into a local cache.
const fs = require("fs");
const path = require("path");
const https = require("https");

const root = __dirname;
const cacheFile = path.join(root, ".babel-standalone.cjs");
const outFile = path.join(root, "bundle.js");

const order = [
  "ticker.jsx",
  "hero.jsx",
  "problem.jsx",
  "inside.jsx",
  "author.jsx",
  "proof.jsx",
  "cta.jsx",
  "faq.jsx",
  "footer.jsx",
  "app.jsx",
];

function fetchTo(url, dest, hops = 0) {
  if (hops > 5) return Promise.reject(new Error("too many redirects"));
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        res.resume();
        return resolve(fetchTo(new URL(res.headers.location, url).toString(), dest, hops + 1));
      }
      if (res.statusCode !== 200) {
        res.resume();
        return reject(new Error("HTTP " + res.statusCode + " from " + url));
      }
      const file = fs.createWriteStream(dest);
      res.pipe(file);
      file.on("finish", () => file.close(() => resolve()));
      file.on("error", reject);
    }).on("error", reject);
  });
}

(async () => {
  if (!fs.existsSync(cacheFile)) {
    console.log("Downloading @babel/standalone (one-time, ~3 MB)...");
    await fetchTo("https://unpkg.com/@babel/standalone@7.29.0/babel.min.js", cacheFile);
    console.log("Cached at " + cacheFile);
  }
  // @babel/standalone is a UMD bundle that references `self`. Provide it in Node.
  if (typeof global.self === "undefined") global.self = global;
  const Babel = require(cacheFile);

  const parts = ["/* Auto-generated by build.js. Edit src/*.jsx, then re-run `node build.js`. */"];
  for (const f of order) {
    const src = fs.readFileSync(path.join(root, "src", f), "utf8");
    const { code } = Babel.transform(src, {
      presets: [["react", { runtime: "classic" }]],
      compact: false,
    });
    parts.push("/* === src/" + f + " === */");
    parts.push(code);
  }
  fs.writeFileSync(outFile, parts.join("\n\n"));
  const size = fs.statSync(outFile).size;
  console.log("Wrote " + outFile + " (" + (size / 1024).toFixed(1) + " KB, " + order.length + " components)");
})().catch((e) => {
  console.error("Build failed:", e.message);
  process.exit(1);
});
